#!/bin/bash

# Job name:
#SBATCH --job-name=Example
#
# Wall time limit
#SBATCH --time=01-00:00:00
#
# Other parameters:
#SBATCH --mem-per-cpu=3G
#SBATCH	--ntasks=16
#SBATCH --chdir=/home/username/path/to/location
## Set up job environment:
set -o errexit  # Exit the script on any error
set -o nounset  # Treat any unset variables as an error

module --quiet purge  # Reset the modules to the system default
module load CMake/3.16.4-GCCcore-9.3.0

## Do some work:
<program line>
